[build]
command = "cd backend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm run db:migrate && npm run start:prod"
healthcheckPath = "/api/lottery/round"
healthcheckTimeout = 100
