[build]
command = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/api/lottery/round"
healthcheckTimeout = 100
